package `fun`.sast.todolist.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006689)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFbfe8ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001e2b)
val md_theme_light_secondary = Color(0xFF4e616c)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd1e6f4)
val md_theme_light_onSecondaryContainer = Color(0xFF0a1e28)
val md_theme_light_tertiary = Color(0xFF006784)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbae9ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001f2a)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfcfe)
val md_theme_light_onBackground = Color(0xFF191c1e)
val md_theme_light_surface = Color(0xFFfbfcfe)
val md_theme_light_onSurface = Color(0xFF191c1e)
val md_theme_light_surfaceVariant = Color(0xFFdce3e9)
val md_theme_light_onSurfaceVariant = Color(0xFF41484d)
val md_theme_light_outline = Color(0xFF71787d)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1f3)
val md_theme_light_inverseSurface = Color(0xFF2e3133)
val md_theme_light_inversePrimary = Color(0xFF71d1ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF71d1ff)
val md_theme_dark_onPrimary = Color(0xFF003549)
val md_theme_dark_primaryContainer = Color(0xFF004d68)
val md_theme_dark_onPrimaryContainer = Color(0xFFbfe8ff)
val md_theme_dark_secondary = Color(0xFFb4c9d6)
val md_theme_dark_onSecondary = Color(0xFF1f333d)
val md_theme_dark_secondaryContainer = Color(0xFF364954)
val md_theme_dark_onSecondaryContainer = Color(0xFFd1e6f4)
val md_theme_dark_tertiary = Color(0xFF61d4ff)
val md_theme_dark_onTertiary = Color(0xFF003546)
val md_theme_dark_tertiaryContainer = Color(0xFF004d64)
val md_theme_dark_onTertiaryContainer = Color(0xFFbae9ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1e)
val md_theme_dark_onBackground = Color(0xFFe1e2e5)
val md_theme_dark_surface = Color(0xFF191c1e)
val md_theme_dark_onSurface = Color(0xFFe1e2e5)
val md_theme_dark_surfaceVariant = Color(0xFF41484d)
val md_theme_dark_onSurfaceVariant = Color(0xFFc0c7cd)
val md_theme_dark_outline = Color(0xFF8a9297)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1e)
val md_theme_dark_inverseSurface = Color(0xFFe1e2e5)
val md_theme_dark_inversePrimary = Color(0xFF006689)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF205e79)
val error = Color(0xFFba1b1b)
